# Generated by Django 4.2.10 on 2025-05-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo en Municipalidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDINATOR', 'Coordinador'), ('MUNICIPAL_MANAGER', 'Encargado Municipal')], default='MUNICIPAL_MANAGER', max_length=20),
        ),
    ]
