# Generated by Django 4.2.10 on 2025-05-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('formulario', 'Formulario'), ('guia', 'Guía'), ('politica', 'Política'), ('otro', 'Otro')], max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('url', models.URLField()),
                ('categoria', models.CharField(choices=[('institucional', 'Institucional'), ('academico', 'Académico'), ('administrativo', 'Administrativo'), ('soporte', 'Soporte'), ('otro', 'Otro')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
