# Generated by Django 4.2.10 on 2025-05-26 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herramientas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoConasec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('categoria', models.CharField(max_length=100)),
                ('tipo_archivo', models.CharField(blank=True, max_length=10)),
                ('tamaño_archivo', models.CharField(blank=True, max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recurso CONASEC',
                'verbose_name_plural': 'Recursos CONASEC',
                'ordering': ['categoria', 'titulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='enlace',
            options={'ordering': ['categoria', 'titulo'], 'verbose_name': 'Enlace', 'verbose_name_plural': 'Enlaces'},
        ),
        migrations.RemoveField(
            model_name='enlace',
            name='usuario_creacion',
        ),
        migrations.AddField(
            model_name='enlace',
            name='icono',
            field=models.CharField(default='fas fa-link', max_length=50),
        ),
        migrations.AddField(
            model_name='enlace',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('manual', 'Manual'), ('guia', 'Guía'), ('formato', 'Formato'), ('directiva', 'Directiva'), ('resolucion', 'Resolución'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='categoria',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('academico', 'Académico'), ('soporte', 'Soporte'), ('normativo', 'Normativo'), ('capacitacion', 'Capacitación'), ('herramienta', 'Herramienta')], max_length=20),
        ),
    ]
