# Generated by Django 4.2.10 on 2025-06-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0003_recursoconasec_alter_enlace_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('prefijo_carpeta', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('permite_municipal', models.BooleanField(default=False, verbose_name='Usuarios Municipales')),
                ('permite_admin', models.BooleanField(default=True, verbose_name='Administradores')),
                ('permite_coordinador', models.BooleanField(default=True, verbose_name='Coordinadores')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['nombre'],
            },
        ),
    ]
