# Generated by Django 4.2.10 on 2025-05-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo_coresec',
            field=models.CharField(blank=True, help_text='Especifica tu cargo en CORESEC', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo_municipal',
            field=models.CharField(blank=True, help_text='Especifica tu cargo municipal', max_length=100, null=True),
        ),
    ]
