# Generated by Django 4.2.10 on 2025-05-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('año', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4)),
                ('trimestre', models.CharField(blank=True, choices=[('1', 'Primer Trimestre'), ('2', 'Segundo Trimestre'), ('3', 'Tercer Trimestre'), ('4', 'Cuarto Trimestre')], max_length=1, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('observado', 'Observado'), ('atendido', 'Atendido'), ('aprobado', 'Aprobado')], default='pendiente', max_length=15)),
                ('archivo_adjunto', models.FileField(upload_to='informes/%Y/%m/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('itca_trimestral', 'Informe Trimestral de Actividades ITCA'), ('anual_seguimiento', 'Informe Anual de Seguimiento'), ('anual_evaluacion', 'Informe Anual de Evaluación'), ('respuesta_trimestral', 'Informe Trimestral de Seguimiento'), ('respuesta_anual', 'Informe Anual de Seguimiento'), ('ficha_verificacion', 'Ficha de Verificación'), ('supervision', 'Informe de Supervisión'), ('its', 'Informe ITS'), ('ias', 'Informe IAS')], max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('itca', 'ITCA'), ('ficha_verificacion', 'Ficha de Verificación'), ('supervisiones', 'Supervisiones'), ('its', 'ITS'), ('ias', 'IAS')], max_length=20)),
                ('requiere_periodo', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Informe',
                'verbose_name_plural': 'Tipos de Informe',
            },
        ),
        migrations.CreateModel(
            name='RespuestaInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='respuestas/%Y/%m/')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='reportes.informe')),
            ],
            options={
                'verbose_name': 'Respuesta de Informe',
                'verbose_name_plural': 'Respuestas de Informe',
                'ordering': ['fecha_respuesta'],
            },
        ),
    ]
