# Generated by Django 4.2.10 on 2025-06-06 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reportes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('año', models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')])),
                ('trimestre', models.IntegerField(blank=True, choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre'), (4, 'Cuarto Trimestre')], null=True)),
                ('fecha_informe', models.DateField(blank=True, help_text='Para Fichas de Verificación y Supervisiones', null=True)),
                ('archivo_adjunto', models.FileField(upload_to=reportes.models.upload_to_structured_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_correccion', 'Requiere Corrección')], default='pendiente', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('informe_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_its', to='reportes.informe')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('prefijo_carpeta', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('permite_municipal', models.BooleanField(default=False)),
                ('permite_admin', models.BooleanField(default=True)),
                ('permite_coordinador', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Respuesta',
                'verbose_name_plural': 'Tipos de Documentos de Respuesta',
            },
        ),
        migrations.CreateModel(
            name='TipoInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nombre_display', models.CharField(max_length=100, verbose_name='Nombre a mostrar')),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('requiere_trimestre', models.BooleanField(default=False)),
                ('requiere_fecha', models.BooleanField(default=False)),
                ('requiere_informe_padre', models.BooleanField(default=False)),
                ('permite_adjuntos', models.BooleanField(default=True)),
                ('estructura_carpetas', models.CharField(default='INFORMES/{municipalidad}/{tipo}/{año}/{periodo}', help_text='Variables disponibles: {municipalidad}, {tipo}, {año}, {periodo}', max_length=255)),
                ('permite_municipal', models.BooleanField(default=False, verbose_name='Usuarios Municipales')),
                ('permite_admin', models.BooleanField(default=True, verbose_name='Administradores')),
                ('permite_coordinador', models.BooleanField(default=True, verbose_name='Coordinadores')),
            ],
            options={
                'verbose_name': 'Tipo de Informe',
                'verbose_name_plural': 'Tipos de Informe',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo de respuesta (PDF, DOC, DOCX, XLS, XLSX)', null=True, upload_to=reportes.models.upload_respuesta_to_structured_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='reportes.informe')),
                ('tipo_documento', models.ForeignKey(help_text='Tipo de documento de respuesta', on_delete=django.db.models.deletion.CASCADE, to='reportes.tipodocumentorespuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta de Informe',
                'verbose_name_plural': 'Respuestas de Informes',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.AddField(
            model_name='informe',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.tipoinforme'),
        ),
        migrations.AddField(
            model_name='informe',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to=settings.AUTH_USER_MODEL),
        ),
    ]
