# Generated by Django 4.2.10 on 2025-06-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0004_tipodocumento'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herramientas.tipodocumento'),
        ),
    ]
