# Generated by Django 4.2.10 on 2025-05-26 20:31

from django.db import migrations, models
import reportes.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='archivo_adjunto',
            field=models.FileField(upload_to=reportes.models.upload_to_structured_path),
        ),
        migrations.AlterField(
            model_name='tipoinforme',
            name='categoria',
            field=models.CharField(choices=[('itca', 'ITCA'), ('ficha_verificacion', 'FICHA_VERIFICACION'), ('supervisiones', 'SUPERVISIONES'), ('its', 'ITS'), ('ias', 'IAS')], max_length=20),
        ),
    ]
