# Generated by Django 4.2.10 on 2025-05-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_informe_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='fecha_informe',
            field=models.DateField(blank=True, help_text='Fecha específica del informe (para Fichas de Verificación y Supervisiones)', null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='informe_padre',
            field=models.ForeignKey(blank=True, help_text='Informe ITCA al que responde este ITS', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_its', to='reportes.informe'),
        ),
        migrations.AlterField(
            model_name='tipoinforme',
            name='nombre',
            field=models.CharField(choices=[('itca', 'ITCA'), ('ficha_verificacion', 'Ficha de Verificación'), ('supervisiones', 'Supervisiones'), ('its', 'ITS'), ('ias', 'IAS')], max_length=100),
        ),
    ]
