# Generated by Django 4.2.10 on 2025-05-26 21:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reportes.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_informe_fecha_informe_informe_informe_padre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informe',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Informe', 'verbose_name_plural': 'Informes'},
        ),
        migrations.AlterModelOptions(
            name='respuestainforme',
            options={'ordering': ['-fecha_respuesta'], 'verbose_name': 'Respuesta de Informe', 'verbose_name_plural': 'Respuestas de Informes'},
        ),
        migrations.RemoveField(
            model_name='informe',
            name='atendido_por',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='fecha_atencion',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='tipoinforme',
            name='categoria',
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoinforme',
            name='permite_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoinforme',
            name='permite_coordinador',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoinforme',
            name='permite_municipal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='informe',
            name='archivo_adjunto',
            field=models.FileField(upload_to=reportes.models.upload_to_structured_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='informe',
            name='año',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')]),
        ),
        migrations.AlterField(
            model_name='informe',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_correccion', 'Requiere Corrección')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha_informe',
            field=models.DateField(blank=True, help_text='Para Fichas de Verificación y Supervisiones', null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='informe_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_its', to='reportes.informe'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='trimestre',
            field=models.IntegerField(blank=True, choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre'), (4, 'Cuarto Trimestre')], null=True),
        ),
        migrations.AlterField(
            model_name='respuestainforme',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='respuestas_informes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='tipoinforme',
            name='nombre',
            field=models.CharField(choices=[('itca', 'ITCA'), ('ficha_verificacion', 'Ficha de Verificación'), ('supervisiones', 'Supervisiones'), ('its', 'ITS'), ('ias', 'IAS')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoinforme',
            name='requiere_periodo',
            field=models.BooleanField(default=False),
        ),
    ]
