# Generated by Django 4.2.10 on 2025-06-05 14:29

import django.core.validators
from django.db import migrations, models
import reportes.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_alter_informe_options_alter_respuestainforme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestainforme',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=reportes.models.upload_respuesta_to_structured_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
    ]
