# Generated by Django 4.2.10 on 2025-06-05 14:39

import django.core.validators
from django.db import migrations, models
import reportes.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_alter_respuestainforme_archivo_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestainforme',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Archivo de respuesta (PDF, DOC, DOCX, XLS, XLSX)', null=True, upload_to=reportes.models.upload_respuesta_to_structured_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
    ]
