# Generated by Django 4.2.10 on 2025-06-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_alter_respuestainforme_archivo_adjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('oficio', 'Oficio'), ('memorando', 'Memorando'), ('carta', 'Carta'), ('informe_tecnico', 'Informe Técnico'), ('acta', 'Acta'), ('resolucion', 'Resolución'), ('dictamen', 'Dictamen'), ('notificacion', 'Notificación'), ('otro', 'Otro Documento')], max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('prefijo_carpeta', models.CharField(help_text='Prefijo para la carpeta (ej: OFICIOS, MEMORANDOS)', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Respuesta',
                'verbose_name_plural': 'Tipos de Documentos de Respuesta',
            },
        ),
        migrations.AddField(
            model_name='respuestainforme',
            name='tipo_documento',
            field=models.ForeignKey(default=1, help_text='Tipo de documento de respuesta', on_delete=django.db.models.deletion.CASCADE, to='reportes.tipodocumentorespuesta'),
            preserve_default=False,
        ),
    ]
